export const PRICE_PLANS = [
  {
    title: "Straw 🌾",
    price: "0",
    bulletPoints: ["Platform access", "AI generator for text and images"],
    crossedBulletPoints: ["ExpoFast starter"],
    ctaText: "Access ExpoFast",
    ctaButtonVariant: "outline",
    ctaUrl: process.env.NEXT_PUBLIC_STRAW_PLAN,
  },
  {
    title: "Wood 🪵",
    slashedPrice: "249",
    price: "199",
    bulletPoints: [
      "ExpoFast starter",
      "API & Database",
      "Stripe configuration",
      "Apple & Google Pay setup",
      "Emails by Resend",
      "Authentication",
      "Documentation x2",
    ],
    crossedBulletPoints: [
      "Discord & Apps showcase",
      "Access to our apps code",
      "Lifetime updates",
    ],
    ctaText: "Buy ExpoFast",
    allThePrevious: true,
    payOnce: true,
    ctaUrl: process.env.NEXT_PUBLIC_WOOD_PLAN,
  },
  {
    title: "Metal 🪙",
    slashedPrice: "299",
    price: "249",
    bulletPoints: [
      "ExpoFast starter",
      "API & Database",
      "Stripe configuration",
      "Apple & Google Pay setup",
      "Emails by Resend",
      "Authentication",
      "Documentation x2",
      "Discord & Apps showcase",
      "Access to our apps code",
      "Lifetime updates",
    ],
    ctaText: "Buy ExpoFast",
    ctaLink: "/#join",
    allThePrevious: true,
    payOnce: true,
    ctaUrl: process.env.NEXT_PUBLIC_METAL_PLAN,
  },
];
